import { useState } from 'react';
import { NavLink, Link, Routes, Route } from 'react-router-dom';
import { ArrowRight, Atom, Building2, Cpu, Globe2, Lightbulb, Menu, Rocket, Shield, Sparkles, X, Zap } from 'lucide-react';

const cities=[
  ['Nexus','Civic life, citizenship and the capital.',Globe2],['Forge','Engineering, robotics, hardware and manufacturing.',Cpu],
  ['Aurora','Art, music, games, design and digital culture.',Sparkles],['Genesis','Biotechnology, life sciences and human development.',Atom],
  ['Horizon','Aerospace, satellites and future habitats.',Rocket],['Quantum','Physics, mathematics and frontier science.',Zap],
  ['Gaia','Climate technology, energy and sustainability.',Shield],['Arcade','Gaming, VR and immersive worlds.',Building2]
];
const stages=['IDEA','DESIGN','RESEARCH','PROTOTYPE','DEVELOP','DEPLOY'];
const projects=[['Personal AI Robot','Forge','Open hardware and adaptable AI for a personal robot.','PROTOTYPE'],['Orbital Garden','Horizon','Resilient food systems for future orbital habitats.','RESEARCH'],['Synthetic Aurora','Aurora','A generative audiovisual world combining music and spatial art.','DEVELOP']];

function Shell({children}){const [open,setOpen]=useState(false);const links=[['Cities','/cities'],['Innovation','/innovation'],['Economy','/economy'],['Constitution','/constitution'],['Citizenship','/citizenship']];return <div className="app"><header className="nav"><div className="container nav-inner"><Link className="brand" to="/"><span className="brand-mark">N</span>NOVA</Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X size={19}/>:<Menu size={19}/>}</button><nav className={`nav-links ${open?'mobile-open':''}`}>{links.map(([label,path])=><NavLink key={path} to={path} onClick={()=>setOpen(false)} className="nav-link">{label}</NavLink>)}<Link className="nav-cta" to="/dashboard">Enter NOVA</Link></nav></div></header>{children}<footer className="footer"><div className="container footer-row"><span>© NOVA Commonwealth</span><span>Imagine It. Build It. Live It.</span><span>Digital civilization · Global community · Future builders</span></div></footer></div>}
function Page({eyebrow,title,children}){return <Shell><main className="page container"><div className="eyebrow">{eyebrow}</div><h1 className="page-title">{title}</h1>{children}</main></Shell>}
function Home(){return <Shell><section className="hero"><div className="container"><div className="eyebrow">A civilization for the future</div><h1>Imagine it.<br/><span className="gradient">Build it.</span><br/>Live it.</h1><p className="lead">NOVA is a digital civilization for people who imagine technologies that do not exist yet—and want a place to turn those ideas into reality.</p><div className="actions"><Link className="button" to="/citizenship">Become a founding citizen <ArrowRight size={17}/></Link><Link className="button secondary" to="/innovation">Explore the Dream Factory</Link></div></div></section><section className="section"><div className="container"><div className="stats"><div className="stat"><strong>08</strong><span>Digital cities</span></div><div className="stat"><strong>∞</strong><span>Ideas to build</span></div><div className="stat"><strong>01</strong><span>Shared civilization</span></div></div><div className="section-head" style={{marginTop:100}}><div><div className="eyebrow">The idea</div><h2>A home for the future-minded.</h2></div><p className="muted" style={{maxWidth:520,lineHeight:1.8}}>NOVA connects inventors, scientists, engineers, artists, creators, gamers and entrepreneurs inside one evolving digital nation.</p></div></div></section><section className="section alt"><div className="container"><div className="section-head"><div><div className="eyebrow">The cities</div><h2>Eight worlds. One NOVA.</h2></div><Link className="muted" to="/cities">View all →</Link></div><div className="grid cities">{cities.map(([name,desc,Icon],i)=><Link className="card city" to="/cities" key={name}><Icon className="city-icon" size={23}/><h3>{name}</h3><p>{desc}</p><span className="tag">0{i+1} · EXPLORE</span></Link>)}</div></div></section><section className="section"><div className="container"><div className="feature"><div className="eyebrow">Dream Factory</div><h2>Ideas are citizens too.</h2><p className="lead">Move an idea through NOVA's pipeline, assemble a team, find research, prototype and eventually deploy something real.</p><div className="grid pipeline" style={{marginTop:40}}>{stages.map((s,i)=><div className="step" key={s}><b>0{i+1}</b><h3>{s}</h3></div>)}</div><Link className="button" style={{marginTop:34}} to="/innovation">Enter Dream Factory <ArrowRight size={17}/></Link></div></div></section></Shell>}
function Cities(){return <Page eyebrow="NOVA territories" title="Eight cities for eight dimensions of the future."><div className="grid cities" style={{marginTop:55}}>{cities.map(([name,desc,Icon],i)=><article className="card city" key={name}><Icon className="city-icon" size={24}/><span className="tag">CITY 0{i+1}</span><h3 style={{marginTop:15}}>{name}</h3><p>{desc}</p></article>)}</div></Page>}
function Innovation(){return <Page eyebrow="Dream Factory" title="Turn impossible ideas into buildable projects."><div className="grid pipeline" style={{marginTop:55}}>{stages.map((s,i)=><div className="step" key={s}><b>0{i+1}</b><h3>{s}</h3></div>)}</div><div className="grid project-grid" style={{marginTop:60}}>{projects.map(([name,city,desc,status])=><article className="card project" key={name}><span className="tag">{city} · {status}</span><h3 style={{marginTop:60}}>{name}</h3><p>{desc}</p><button className="button secondary" style={{marginTop:20}}>View project →</button></article>)}</div><div className="panel" style={{marginTop:25}}><Lightbulb color="var(--cyan)"/><h2 style={{fontSize:30}}>Have an idea?</h2><p className="muted">Create a project with a problem, solution, requirements, team, budget and roadmap.</p><button className="button" style={{marginTop:15}}>Create project</button></div></Page>}
function Economy(){return <Page eyebrow="Nexa economy" title="An economy designed to reward creation."><div className="grid two-col" style={{marginTop:55}}><div className="panel"><div className="eyebrow">Conceptual currency</div><div style={{fontSize:62,fontWeight:900,marginTop:15}}>◈ Nexa</div><p className="muted">NXA · Maximum authorized supply: 100,000,000,000</p><p className="lead" style={{fontSize:17}}>Currency flows toward creation. The long-term vision supports software, hardware, research, education, art, services and entrepreneurship.</p></div><div className="panel"><div className="eyebrow">Proposed ecosystem</div>{[['Treasury','30%'],['Citizen Reserve','20%'],['Innovation Fund','20%'],['Infrastructure','10%'],['Education & Research','10%']].map(([a,b])=><div className="list-item" style={{marginTop:10,display:'flex',justifyContent:'space-between'}} key={a}><span>{a}</span><span style={{color:'var(--cyan)'}}>{b}</span></div>)}</div></div><div className="notice" style={{marginTop:25}}>Nexa is conceptual demonstration data. NOVA does not issue cryptocurrency or provide banking, custody, payment or investment services.</div></Page>}
function Constitution(){return <Page eyebrow="Founding charter" title="A civilization where people remain sovereign over the future."><div className="grid two-col" style={{marginTop:55}}><div className="panel"><h2 style={{fontSize:30}}>Founding principles</h2><div className="list">{['Innovation','Freedom of Creation','Knowledge','Collaboration','Merit','Responsibility','Humanity'].map(x=><div className="list-item" key={x}>{x}</div>)}</div></div><div className="panel"><h2 style={{fontSize:30}}>Core rights</h2><p className="lead" style={{fontSize:16}}>Freedom of creation and association. Access to knowledge. Privacy. Economic participation. Due process. Transparent governance. The right to leave NOVA.</p><h2 style={{fontSize:30,marginTop:45}}>Human accountability</h2><p className="muted" style={{lineHeight:1.8}}>AI can assist NOVA, but significant civic decisions remain accountable to humans.</p></div></div></Page>}
function Citizenship(){return <Page eyebrow="Citizenship" title="Claim your place in the founding generation."><div className="panel" style={{maxWidth:650,marginTop:55}}><p className="muted">Founding citizen registration</p><div className="list"><input className="field" placeholder="Display name"/><input className="field" placeholder="Email" type="email"/><input className="field" placeholder="What do you want to build?"/><button className="button">Create NOVA identity</button></div><p className="muted" style={{fontSize:12,marginTop:20}}>MVP registration only. Persistent identity and authentication will connect to NOVA services as they are built.</p></div></Page>}
function Dashboard(){return <Page eyebrow="Citizen OS" title="Welcome to NOVA."><div className="grid two-col" style={{marginTop:55}}><div className="panel"><div className="eyebrow">Digital passport</div><h2 style={{fontSize:34}}>Founding Citizen</h2><p className="muted">Status: Pioneer · Residence: Nexus</p><div className="grid" style={{gridTemplateColumns:'repeat(3,1fr)',marginTop:35}}>{[['◈','Nexa Wallet','Demo'],['◈','Projects','3 active'],['◈','Civic','0 proposals']].map(([a,b,c])=><div className="list-item" key={b}><span style={{color:'var(--cyan)'}}>{a}</span><strong style={{display:'block',marginTop:12}}>{b}</strong><small className="muted">{c}</small></div>)}</div></div><div className="panel"><div className="eyebrow">Quick action</div><h2 style={{fontSize:30}}>Build something.</h2><p className="muted">Your next invention starts as an idea.</p><Link className="button" to="/innovation">Create project <ArrowRight size={17}/></Link></div></div></Page>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/cities" element={<Cities/>}/><Route path="/innovation" element={<Innovation/>}/><Route path="/economy" element={<Economy/>}/><Route path="/constitution" element={<Constitution/>}/><Route path="/citizenship" element={<Citizenship/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="*" element={<Home/>}/></Routes>}
export default App;
